### ISSUE TITLE
Words based diff

### ISSUE THREAD

**Issue by naumanzchaudhry** [praneshr/react-diff-viewer#28]
Hi, pretty useful work. Currently it shows diff based on characters. How can we show diff based on words. 

Just like this one [words-based-diff](http://cezary.github.io/react-diff/)

**Comment by praneshr** [comment]
Hi @naumanzchaudhry, I don't have a plan for supporting word diff soon. As the component shows line level and character level diff, word diff is not required. That said, if there's a lot of ask for word diff then I might support. Thanks.

**Comment by Avnerus** [comment]
Actually it seems very easy to add word diff support. Just change in [here](https://github.com/praneshr/react-diff-viewer/blob/master/src/compute-lines.ts#L69) from:
` .diffChars(oldValue, newValue);`
to:
` .diffWords(oldValue, newValue);`
It makes it much easier to look at differences in text values, because the character diff highlights specific characters inside changed words instead of the whole word.
Thank you for this great component!
